apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pv1.yaml
  - pv2.yaml
  - pv3.yaml
  - db.yaml
  - scheduler.yaml
  - scheduler-service-account.yaml
  - server.yaml
  - volume-configs.yaml
  - volume-db.yaml
  - volume-workspace.yaml
  - webapp.yaml
  - temporal.yaml
  - airbyte-lb-web.yaml