apiVersion: v1
kind: PersistentVolume
metadata:
  name: airbyte-1-pv-1
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: scw-bssd
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                 - scw-cluster-dev-core-30ed3714585e4fd8a6c129900